from __future__ import annotations
from abc import ABC, abstractmethod

class DobotDriver(ABC):
    @abstractmethod
    def connect(self): ...
    @abstractmethod
    def close(self): ...
    @abstractmethod
    def snapshot(self) -> dict: ...
    @abstractmethod
    def execute(self, command: str, payload: dict, allow_motion: bool) -> None: ...
